import "@styles/globals.scss"; // 🔥 Importar primero los estilos globales
import "@styles/custom-classes.css"; // Otros estilos globales

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@components/layout/Header";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "My Next.js 15 App",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (

        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
        </body>
        </html>
    );
}
