import "@styles/globals.scss";
// import "@styles/index.module.scss";
import Header from "@components/layout/Header";
import Footer from "@components/layout/Footer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Header />
        <div className="layout">
            <main className="content">{children}</main>
        </div>
        <Footer />
        </body>
        </html>
    );
}

// const inter = Inter({ subsets: ["latin"] });
//
// export default function RootLayout({ children }: { children: ReactNode }) {
//     return (
//         <html lang="es">
//         <body className={inter.className}>
//         <Header />
//         <div className="layout">
//             <main className="content">{children}</main>
//         </div>
//         <Footer />
//         </body>
//         </html>
//     );
// }
